### ISSUE TITLE
token has expired error

### ISSUE THREAD

**Issue by kurokirasama** [ThomasHabets/cmdg#109] opened 2023-03-26 00:21 UTC
Hey, regularly I get this error:
```
FATA[0000] Failed to load signature from Drive appdata: Get "https://www.googleapis.com/drive/v3/files?alt=json&pageToken=&prettyPrint=false&spaces=appDataFolder": oauth2: cannot fetch token: 400 Bad Request
Response: {
  "error": "invalid_grant",
  "error_description": "Token has been expired or revoked."
}
```
And I have to re-configure. Any way to avoid this?

**Comment by ThomasHabets** [comment] 2023-03-26 22:28
Regularly? Huh. That's odd.

It's impossible to know Google's internal risk systems (probably impossible for someone even on that team, as I'm sure it's full of machine learning).

I think all cmdg can do is to streamline re-configure a bit.

`-configure` is not really the best name for it, as all we "configure" is the auth token. Everything else (any signature, contacts, emails themselves) are all in the Google Cloud.

How often would you say that you get this?

Oh, and are you doing anything that may be suspicious, like us the *same* auth token (`cmdg.conf` file) on multiple machines?

**Comment by kurokirasama** [comment] 2023-03-27 04:19
Thanks for the response.
I would say every two weeks maybe.

I do have cmdg running in two different machines, but I "configure" them independently. 

It would be cool if we could pass the CliendID and ClientSecret directly trough a flag maybe...

Regards,

**Comment by mwiseley-wakefly** [comment] 2023-04-24 14:59
Getting the same behavior, and similar use case - two machines with separate configs (but the same client ID/secret).

**Comment by ThomasHabets** [comment] 2023-04-24 17:16
It's curious. I think I've had to do this once in 9 years. I use the same client ID/secret on multiple machines, but they've run `-configure` separately.

I think maybe a cleaner way to do this than reading from the command line is to read it from the config file and reuse it.

That and detecting the situation and automatically starting a reconfiguring on startup.

**Comment by ThomasHabets** [comment] 2023-04-26 22:48
Do you use cmdg every day, or could it be that google expires the refresh token because lack of recent use?

**Comment by kurokirasama** [comment] 2023-04-26 22:49
I use it daily

**Comment by ThomasHabets** [comment] 2023-04-30 14:07
I've improved the situation so that `-configure` will reuse any existing ClientID/ClientSecret in the current config file.

Oh, maybe you are experiencing [this problem](https://stackoverflow.com/questions/66058279/token-has-been-expired-or-revoked-google-oauth2-refresh-token-gets-expired-i)?

**Comment by kurokirasama** [comment] 2023-05-01 03:46
cool! I just updated, let's see how it does this week. I don't have any test users so that's not my issue

**Comment by ThomasHabets** [comment] 2023-05-01 10:35
You don't have any test users, but could your "Publishing status" be "Testing"?

Mine is "In production", and it can be seen on [this page in the cloud console](https://console.cloud.google.com/apis/credentials/consent).

**Comment by mwiseley-wakefly** [comment] 2023-05-01 12:40
Confirmed my app was in testing mode. I've published it - good find! Thanks for the token reuse change - I've appreciated this feature in rclone.

**Comment by kurokirasama** [comment] 2023-05-01 17:51
True, I was in testing mode too... Now that I've changed it to In production, are the verification steps necessary?

**Comment by ThomasHabets** [comment] 2023-05-01 18:09
My consent screen still says "Verification status / Verification in progress". It's been like that for years, with no progress. The only way it seems to affect me is that I have to click past an extra warning during the oauth flow.

Maybe you'll have more luck with review speed. But no, it should not be necessary. Has worked fine for me.

Thanks for confirming that this was the cause. I'll close the issue, but I'd be interested in hearing any oauth and consent screen updates if you have them.

**Closed by ThomasHabets** 2023-05-01 18:09 UTC
Labels: enhancement

**Comment by kurokirasama** [comment] 2023-05-01 18:14
Cool! Thanks!
